# Arrays

available in numpy

optimized for computational performance

In [1]:
import numpy as np

In [5]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
x = np.arange(0,20)
x


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
x[2] = 12
x

array([ 0,  1, 12,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
x.dtype

dtype('int64')

In [15]:
x[10] = "abcd"

ValueError: invalid literal for int() with base 10: 'abcd'

In [18]:
x.pop()

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

In [20]:
x.append(3)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [22]:
np.random.rand(5,5)

array([[ 0.10255913,  0.83506888,  0.18183391,  0.051397  ,  0.42071607],
       [ 0.11474137,  0.98666953,  0.68793415,  0.56520256,  0.20922355],
       [ 0.08373955,  0.62794957,  0.02556085,  0.24680744,  0.19993966],
       [ 0.5823502 ,  0.74592413,  0.62600173,  0.51983646,  0.62932912],
       [ 0.02198428,  0.8697764 ,  0.45300575,  0.94961451,  0.6802887 ]])

In [24]:
np.random.rand(5,5,5)

array([[[ 0.52977985,  0.91908957,  0.83978767,  0.54623148,  0.12262097],
        [ 0.68256966,  0.89706919,  0.45592227,  0.97352545,  0.93096239],
        [ 0.42639652,  0.85448206,  0.34371754,  0.03367006,  0.34058131],
        [ 0.61594494,  0.92835065,  0.79326455,  0.84582771,  0.44049249],
        [ 0.01810077,  0.29653143,  0.69785823,  0.50100152,  0.90085376]],

       [[ 0.90632673,  0.90337423,  0.54335846,  0.94422755,  0.97769955],
        [ 0.69957852,  0.53175619,  0.7994875 ,  0.63360875,  0.98363862],
        [ 0.17034726,  0.12824401,  0.27692785,  0.13271694,  0.92805321],
        [ 0.32730785,  0.0721199 ,  0.62049816,  0.51641837,  0.10859007],
        [ 0.73430802,  0.7403576 ,  0.99989684,  0.25951505,  0.32896552]],

       [[ 0.92272339,  0.08165542,  0.2666094 ,  0.77963862,  0.53181509],
        [ 0.36844876,  0.68172071,  0.69248202,  0.71323662,  0.16025038],
        [ 0.76619151,  0.47905964,  0.17725966,  0.08739819,  0.73780871],
        [ 0.99973669,

In [26]:
np.random?

In [28]:
np.random.randn(20)

array([ 0.37663254,  1.27148438,  0.81873423, -0.07266569,  0.31075631,
        0.10295606, -0.22545556,  1.53893717,  1.54000159, -0.31198426,
        0.46867018,  0.83946494, -1.6540726 ,  0.67343492,  1.44428821,
        0.55326354, -1.85116151, -0.75620548, -2.00456977,  1.10140685])

In [29]:
ar = np.random.randn(20)
ar

array([-1.11230745,  0.78433219,  1.00489027, -0.05684344, -1.65775457,
       -0.15507541,  0.8009685 , -0.15697492, -0.07609391,  0.81849987,
        1.75743625, -0.299804  ,  0.38348179, -0.85707105, -0.2245469 ,
        0.20916725, -0.51946147, -1.25363498,  1.06772034,  0.28164339])

In [30]:
ar.mean()

0.036928587331683804

In [31]:
ar.std()

0.84164556541991586

In [33]:
ar = ar.reshape(5,4)
ar

array([[-1.11230745,  0.78433219,  1.00489027, -0.05684344],
       [-1.65775457, -0.15507541,  0.8009685 , -0.15697492],
       [-0.07609391,  0.81849987,  1.75743625, -0.299804  ],
       [ 0.38348179, -0.85707105, -0.2245469 ,  0.20916725],
       [-0.51946147, -1.25363498,  1.06772034,  0.28164339]])

In [35]:
ar.mean(axis = 0)

array([-0.59642712, -0.13258987,  0.88129369, -0.00456234])

In [36]:
ar.mean(axis = 1)

array([ 0.15501789, -0.2922091 ,  0.55000955, -0.12224223, -0.10593318])